CLANG_FLAGS += -Werror=no-typedef-redefinition

obj-$(CONFIG_AMLOGIC_MEDIA_MODULES) += amvdec_ports.o
amvdec_ports-objs += aml_vcodec_dec_drv.o
amvdec_ports-objs += aml_vcodec_dec.o
amvdec_ports-objs += aml_vcodec_dec_pm.o
amvdec_ports-objs += aml_vcodec_util.o
amvdec_ports-objs += aml_vcodec_adapt.o
amvdec_ports-objs += aml_vcodec_vfm.o
amvdec_ports-objs += vdec_drv_if.o
amvdec_ports-objs += decoder/vdec_h264_if.o
amvdec_ports-objs += decoder/vdec_vp9_if.o
amvdec_ports-objs += decoder/vdec_hevc_if.o
amvdec_ports-objs += decoder/h264_parse.o
amvdec_ports-objs += decoder/h264_stream.o
