obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	common/
obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	frame_provider/
obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	frame_sink/
obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	stream_input/
obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	amvdec_ports/
