
#
# Makefile for the goodix touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GTS) += gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GTS) += gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GTS) += goodix_tool.o

