obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	 stream_input.o

stream_input-objs	+=	amports/amstream.o
stream_input-objs	+=	amports/amstream_profile.o
stream_input-objs	+=	amports/adec.o
stream_input-objs	+=	parser/thread_rw.o
stream_input-objs	+=	parser/streambuf.o
stream_input-objs	+=	parser/esparser.o
stream_input-objs	+=	parser/tsdemux.o
stream_input-objs	+=	parser/psparser.o
stream_input-objs	+=	parser/rmparser.o
stream_input-objs	+=	subtitle/subtitle.o

obj-$(CONFIG_AMLOGIC_DVB) += parser/hw_demux/
# obj-$(CONFIG_AMLOGIC_MEDIA_MODULES) 	+= 	tv_frontend/
# obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	box-frontend/avl6211/
# obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	box-frontend/atbm8881/
# obj-$(CONFIG_AMLOGIC_MEDIA_MODULES)	+=	box-frontend/avl68xx/
